variables:
    SolutionBaseName: 'DFC.App.JobProfile.RefreshSegments'
    ArmTemplateRoot: "$(System.DefaultWorkingDirectory)/Resources/ArmTemplates"
    BuildPlatform: 'any cpu'
    BuildConfiguration: 'release'

resources:
  repositories:
  - repository: self
  - repository: dfc-devops
    type: github
    name: SkillsFundingAgency/dfc-devops
    ref: refs/tags/v1.15.0
    endpoint: 'SkillsFundingAgency'

pool:
  name: NCS - CI and CD
  demands:
  - msbuild
  - visualstudio

stages:
- stage: Build
  jobs:
  - job:
    displayName: Build and test application & templates
    steps:
    - template: /AzureDevOpsTemplates/Build/StepTemplates/dfc-arm-build.yml@dfc-devops
      parameters:
        ArmTemplateRoot: '${{ variables.ArmTemplateRoot }}'
        SolutionBaseName: '${{ variables.SolutionBaseName }}'

    - template: AzureDevOpsTemplates\Build\StepTemplates\dfc-dotnetcore-build-notests.yml@dfc-devops
      parameters:
        SolutionBaseName: $(SolutionBaseName)
        BuildPlatform: $(BuildPlatform)
        BuildConfiguration: $(BuildConfiguration)
        PublishWebApp: true

- stage: DeployToDev
  dependsOn: Build
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  displayName: Deploy to DEV
  variables:
  - group: dfc-shared-dev
  - group: dfc-app-shared-all
  - group: dfc-shared-all
  - group: dfc-stax-shared-dev
  - group: dfc-stax-shared-all
  - group: dfc-app-shared-dev
  - group: 'KeyVault - dfc-dev-shared-kv'
  - template: VariableTemplates/DevEnvironmentVariables.yml
  jobs:
  - template: JobTemplates/deploy-environment.yml
    parameters:
      AzureSubscription: 'SFA-CDH-Dev/Test (962cae10-2950-412a-93e3-d8ae92b17896)'
      EnvironmentTag: '$(EnvironmentTag)'
      ParentBusiness: '$(ParentBusiness)'
      ServiceOffering: '$(ServiceOffering)'
      ResourceGroup: '$(ResourceGroup)'
      PackageFile:  "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.DeploymentPackages/DeploymentPackages/${{ variables.SolutionBaseName }}/${{ variables.SolutionBaseName }}.zip"
      ArmTemplateFolder: "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.Resources.ArmTemplates/"
      EnvironmentName: DEV_AppJobProfRefSeg
      DFCAzureDevOpsProjectGuid: $(DFCAzureDevOpsProjectGuid)
      SharedResourceGroup: "$(SharedResourceGroup)"
      DfCDevopsPath: '$(Agent.BuildDirectory)/s/dfc-devops'
      AppSharedResourceGroup: $(AppSharedResourceGroup)
      FunctionAppName: $(functionAppName)
