parameters:
  AzureSubscription: ''
  SetEsfaResourceGroupTagsScript: 'https://raw.githubusercontent.com/SkillsFundingAgency/dfc-devops/master/PSScripts/Set-EsfaResourceGroupTags.ps1'
  PackageFile:  ''
  ArmTemplateFolder: ''
  Location: 'West Europe'
  ArmOutputVariableName: 'ARMOutputs'
  EnvironmentTag: 'DEV/Test'
  ParentBusiness: ''
  ServiceOffering: ''
  ResourceGroup: ''
  EnvironmentName: ''
  DFCAzureDevOpsProjectGuid: ''
  DfcContentTestsBuildId: ''
  SharedResourceGroup: ''
  DfCDevopsPath: ''
  AppSharedResourceGroup: ''

jobs:
- deployment: DeployTemplate
  displayName: "Deploy arm templates"
  environment: ${{ parameters.EnvironmentName }}
  strategy:
    runOnce:
      deploy:
        steps:
        - template: ../StepTemplates/deploy-arm-template.yml
          parameters: 
            AzureSubscription: '${{ parameters.AzureSubscription }}'
            SetEsfaResourceGroupTagsScript: '${{ parameters.SetEsfaResourceGroupTagsScript }}'
            EnvironmentTag: '${{ parameters.EnvironmentTag }}'
            ParentBusiness: '${{ parameters.ParentBusiness }}'
            ServiceOffering: '${{ parameters.ServiceOffering }}'
            ResourceGroup: '${{ parameters.ResourceGroup }}'
            Location: '${{ parameters.Location }}'
            ArmOutputVariableName: '${{ parameters.ArmOutputVariableName }}'
            ArmTemplateFolder: '${{ parameters.ArmTemplateFolder }}'
            DfCDevopsPath: '${{ parameters.DfCDevopsPath }}'
            AppSharedResourceGroup: '${{ parameters.AppSharedResourceGroup }}'

- deployment: DeployFunctionApp
  displayName: "Deploy ${{ parameters.FunctionAppName }}"
  environment: ${{ parameters.EnvironmentName }}
  dependsOn: 
  - DeployTemplate
  strategy:
    runOnce:
      deploy:
        steps:
        - template: ../StepTemplates/deploy-functionapp.yml
          parameters:
            WebAppName: '${{ parameters.FunctionAppName }}'
            AzureSubscription: '${{ parameters.AzureSubscription }}'
            PackageFile: '${{ parameters.PackageFile }}'
            ResourceGroup: '${{ parameters.ResourceGroup }}'