variables:
- name: ExceptionCountThreshold
  value: 10
- name: EnableAzureMonitorAlerting
  value: true
- name: ReleaseEnvironmentName
  value: lab
- name: WebAppPrefix
  value: dfc-lab-app-jobprof-refseg
- name: FunctionAppInsightName
  value: $(WebAppPrefix)-ai
- name: FunctionAppName
  value: $(WebAppPrefix)-fa
- name: ResourceGroup
  value: $(WebAppPrefix)-rg