variables:
- name: aspInstances
  value: 2
- name: aspSize
  value: 2
- name: aspTier
  value: Standard
- name: ExceptionCountThreshold
  value: 10
- name: EnableAzureMonitorAlerting
  value: true
- name: ReleaseEnvironmentName
  value: pp
- name: WebAppPrefix
  value: dfc-pp-app-jobprof-refseg
- name: FunctionAppInsightName
  value: $(WebAppPrefix)-ai
- name: FunctionAppName
  value: $(WebAppPrefix)-fa
- name: ResourceGroup
  value: $(WebAppPrefix)-rg